### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by ghost** [ObelusFamily/Anythink-Market-j13b1#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by gbj1220** [comment]
![Screenshot 2023-01-28 at 5 07 02 PM](https://user-images.githubusercontent.com/71044539/215293184-bff8e8de-5583-483c-b449-7568d87d48f0.png)
